### PR TITLE
Adding a statement about unit testing in README

### PR DESCRIPTION
**Pull request by jessethach**
- Writing unit tests is highly encouraged. Unit testing will bring immediate value to your project and increase the likelihood of moving forward in our process.

### CODE REVIEW

**Comment by CarteriTrellis** [comment]
I would delete the second sentence entirely.

**Comment by jessethach** [comment]
Why's that?

**Comment by CarteriTrellis** [comment]
It’s more consistent with what we do with our other code projects. It also lets the candidate make their own decision as to the value of tests, which is an interesting test in and of itself.

**Comment by jessethach** [comment]
Agreed that it's a good test for the candidate. I also think that there haven't been much unit testing in projects lately, so I wanted clear language to encourage testing.

**Comment by itrelouis** [comment]
I think I agree with Carter. Maybe we can make it bold and italicized as a compromise

**Comment by jessethach** [comment]
Thanks @itrelouis - thoughts @alexhebert-itrellis?

**Comment by alexhebert-itrellis** [comment]
I agree with Carter and Louis. I think the second sentence is too "on the nose" and just a passing mention of unit tests should be enough. Like Carter said, I think there's value in measuring how people react to the unit test requirement without going into much detail beyond that.

**Comment by jessethach** [comment]
This is when A/B testing would come in handy. I'll remove the second sentence.

**Pull request merged**
